### ISSUE TITLE
rake db:migrate:extensions fails with error: uninitialized constant ActiveRecord::Base::VersionsProxyMethods

### ISSUE THREAD

**Issue by reagent** [jgarber/radiant-chronicle-extension#17]
I was testing out your extension on a fresh installation of Radiant 0.7.1 - when I went to run `rake db:migrate:extensions`, I got the following error (stacktrace included):

```
$ rake db:migrate:extensions --trace
(in /Users/preagan/Projects/radiant-test)
** Invoke db:migrate:extensions (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
uninitialized constant ActiveRecord::Base::VersionsProxyMethods
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:493:in `const_missing'
/Users/preagan/Projects/radiant-test/vendor/extensions/chronicle/chronicle_extension.rb:19:in `activate'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/extension.rb:38:in `activate'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activesupport/lib/active_support/core_ext/symbol.rb:11:in `__send__'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activesupport/lib/active_support/core_ext/symbol.rb:11:in `to_proc'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/extension_loader.rb:94:in `each'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/extension_loader.rb:94:in `activate_extensions'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/initializer.rb:122:in `after_initialize'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/railties/lib/initializer.rb:152:in `process'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/railties/lib/initializer.rb:97:in `send'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/railties/lib/initializer.rb:97:in `run'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/lib/radiant/initializer.rb:101:in `run'
/Users/preagan/Projects/radiant-test/config/environment.rb:12
/opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
/opt/local/lib/ruby/gems/1.8/gems/radiant-0.7.1/vendor/rails/railties/lib/tasks/misc.rake:3
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:617:in `call'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:617:in `execute'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:612:in `each'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:612:in `execute'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:578:in `invoke_with_call_chain'
/opt/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:571:in `invoke_with_call_chain'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:588:in `invoke_prerequisites'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:585:in `each'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:585:in `invoke_prerequisites'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:577:in `invoke_with_call_chain'
/opt/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:571:in `invoke_with_call_chain'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:564:in `invoke'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2027:in `invoke_task'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2005:in `top_level'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2005:in `each'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2005:in `top_level'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2044:in `standard_exception_handling'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:1999:in `top_level'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:1977:in `run'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:2044:in `standard_exception_handling'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/lib/rake.rb:1974:in `run'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.4/bin/rake:31
/opt/local/bin/rake:19:in `load'
/opt/local/bin/rake:19
```

**Comment by cristi** [comment]
I think you need to run "git submodule init" and "git submodule update" inside the extension's folder.. to update the plugins. It uses the simple_versioned plugin.

Hope this helps.

**Comment by jgarber** [comment]
Yes, that's right.  I'll add it to the README.

**Comment by jgarber** [comment]
Add submodule commands to installation instructions in the README. Closed by 6b7331c879953c3a167b2170c275932c77c90a6d

**Comment by reagent** [comment]
Thanks, guys - works great.

**Comment by rud** [comment]
Heads up: the "git submodule init" and "git submodule update" must be run both in the vendor/extension/chronicle folder, as well as the main project folder.

This is not currently clear from the installation instructions - please update.

**Comment by jgarber** [comment]
Good call, rud.  Sorry 'bout that.  Fixed.

**Comment by rud** [comment]
Excellent - thanks!

**Comment by lag-zz** [comment]
I got this after pushing to heroku. Heroku people need to seek and destroy ALL .git folders (not just vendor/extensions/*/.git) and git-add the new files before pushing to heroku.
